import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Animate.module.sass";
import Link from "next/link";
import { useEffect, useState } from "react";
import Script from "next/script";


export default function AnimatePage() {
  const [createJSLoaded, setCreateJSLoaded] = useState(false);
  let canvas, exportRoot, anim_container, dom_overlay_container, fnStartAnimation;

  const onScriptLoad = () => {
    init();
  };

  const init = () => {
    canvas = document.querySelector("#canvas");
    anim_container = document.querySelector("#animation_container");
    dom_overlay_container = document.querySelector("#dom_overlay_container");
    var comp = AdobeAn.getComposition("2CB510DBC8F54631B10DFB31ED50C6A2");
    var lib = comp.getLibrary();
    handleComplete({}, comp);
  }
  const handleComplete = (evt, comp) => {
    console.log("handleComplete");
    var lib = comp.getLibrary();
    var ss = comp.getSpriteSheet();
    exportRoot = new lib.cake();
    window.stage1 = new lib.Stage(canvas);
    window.stage1.enableMouseOver();
    fnStartAnimation = function () {
      window.stage1.addChild(exportRoot);
      createjs.Ticker.framerate = lib.properties.fps;
      createjs.Ticker.addEventListener("tick", window.stage1);
    };
    AdobeAn.makeResponsive(false, "both", false, 1, [
      canvas,
      anim_container,
      dom_overlay_container,
    ]);
    AdobeAn.compositionLoaded(lib.properties.id);
    fnStartAnimation();
  }


  return (
    <>
      <Head>
        <title>Adobe Animate Canvas in Next.js</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Script
        src="/createjs.min.js"
        onReady={() => setCreateJSLoaded(true)}
      />
      {createJSLoaded && (
        <>
          <Script
            src="/cake.js"
            type="text/javascript"
            onReady={onScriptLoad}
          />
        </>
      )}
      <main className="container pt-5">
        <h1>Animate Canvas</h1>
        <div id="animation_container" className={styles.container}>
          <canvas id="canvas" className={styles.canvas}></canvas>
          <div id="dom_overlay_container" className={styles.overlay}></div>
        </div>
        <div className="d-flex">
          <Link className="btn btn-warning text-white btn-sm ms-auto" href="/">Back</Link>
        </div>
      </main>
    </>
  );
}
