import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import Link from "next/link";


export default function Home() {
  return (
    <>
      <Head>
        <title>Adobe Animate Canvas in Next.js</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container pt-5">
        <Link className="btn btn-primary" href="/animate">Go to Animate Page 1</Link><br />
      </main>
    </>
  );
}
